Add needpie: requires MISSING matplotlib option
Prove the new matplotlib limiter works, as `make docs` fails with a
warning about missing matplotlib install:

    Running Sphinx v5.2.3
    [...]
    reading sources... [ 25%] architecture
    Exception occurred:
    File "[...]/sphinx-needs-test/.venv/lib/python3.10/site-packages/sphinx_needs/directives/needpie.py", line 36, in error_on_missing_matplotlib
        raise ImportError(
    ImportError: Missing matplotlib/numpy dependency required for needpie directive. Please install sphinxcontrib-needs with optional [matplotlib] flag